### ISSUE TITLE
Privacy considerations

### ISSUE THREAD

**Issue by ionut-arm** [tls-attestation/draft-tls-attestation#1]
One of the missing sections from the draft is some discussion (even if brief) of the privacy considerations of this new extension/credential type. This has also been mentined previously in the discussions following IETF presentations.

One relevant idea to mention is the composability of our extension with [Encrypted Client Hello (ECH)](https://datatracker.ietf.org/doc/html/draft-ietf-tls-esni). This allows some level of privacy by hiding the details of the "main" handshake (including the attestation metadata) from an intermediate (proxy) endpoint. ECH should be perfectly composable/orthogonal to this extension - worth documenting.

Feel free to discuss below any other proposals or ideas related to this topic.

**Comment by yaronf** [comment]
@thomas-fossati I'm not sure about your second mitigation. Isn't the problem that the Attester doesn't want to be tracked by the RP?

Also, assuming there could be a third party Verifier that's trusted by both Attester and RP, is there a way to ensure that the Evidence is only processed by this saintly Verifier and cannot be leaked to anyone else?

**Comment by thomas-fossati** [comment]
> @thomas-fossati I'm not sure about your second mitigation. Isn't the problem that the Attester doesn't want to be tracked by the RP?

The RP is the attester's TLS peer, therefore "tracking" by the RP is unavoidable.

> Also, assuming there could be a third party Verifier that's trusted by both Attester and RP, is there a way to ensure that the Evidence is only processed by this saintly Verifier and cannot be leaked to anyone else?

This needs overloading the word "trusted" :-)

**Comment by yaronf** [comment]
> > @thomas-fossati I'm not sure about your second mitigation. Isn't the problem that the Attester doesn't want to be tracked by the RP?
> 
> The RP is the attester's TLS peer, therefore "tracking" by the RP is unavoidable.
> 
I'm not sure this is a real-life use case, but I can think of scenarios where the RP wants to verify that the Attester is running on a secure platform but we still don't want it to know the Attester's individual identity.

> > Also, assuming there could be a third party Verifier that's trusted by both Attester and RP, is there a way to ensure that the Evidence is only processed by this saintly Verifier and cannot be leaked to anyone else?
> 
> This needs overloading the word "trusted" :-)

Correct. Trusted by the RP to be an honest verifier, and trusted by the Attester not to divulge any information about it.

**Comment by thomas-fossati** [comment]
> > > @thomas-fossati I'm not sure about your second mitigation. Isn't the problem that the Attester doesn't want to be tracked by the RP?
> > 
> > 
> > The RP is the attester's TLS peer, therefore "tracking" by the RP is unavoidable.
> 
> I'm not sure this is a real-life use case, but I can think of scenarios where the RP wants to verify that the Attester is running on a secure platform but we still don't want it to know the Attester's individual identity.

Right. That could be handled via claim redaction / selective disclosure, I think.

**Comment by yaronf** [comment]
> > > > @thomas-fossati I'm not sure about your second mitigation. Isn't the problem that the Attester doesn't want to be tracked by the RP?
> > > 
> > > 
> > > The RP is the attester's TLS peer, therefore "tracking" by the RP is unavoidable.
> > 
> > 
> > I'm not sure this is a real-life use case, but I can think of scenarios where the RP wants to verify that the Attester is running on a secure platform but we still don't want it to know the Attester's individual identity.
> 
> Right. That could be handled via claim redaction / selective disclosure, I think.

I don't think claim redaction is effective, or more precisely its effectiveness depends a lot on the fine details of the Attester (exactly what gets signed). Wasn't [DAA](https://en.wikipedia.org/wiki/Direct_Anonymous_Attestation) supposed to solve this very problem? Is this technology still relevant?

**Comment by thomas-fossati** [comment]
> I don't think claim redaction is effective, or more precisely its effectiveness depends a lot on the fine details of the Attester (exactly what gets signed).
> Wasn't [DAA](https://en.wikipedia.org/wiki/Direct_Anonymous_Attestation) supposed to solve this very problem?

Yes, DAA prevents the verifier from learning the identity of the individual signer/attester within a known group, but the attester can still reveal a lot of identifying information in the evidence claims.

(Anonymity groups can also be created at manufacturing time if the same crypto credential and instance identifier are assigned to a batch of devices - see FIDO key attestation.)

> Is this technology still relevant?

AFAIK, EPID is used in FDO (i.e., for device onboarding).
